'use client';

import type { CanvasNode, ModelConfig } from '../../lib/canvas/types';

type Props = { node: CanvasNode | null; models: ModelConfig[]; connected: string[]; onChange: (patch: Partial<CanvasNode['data']>) => void; onRun: () => void; onClose: () => void; onDelete: () => void; onDuplicate: () => void };
const labelMap = { text: '文字', image: '图片', video: '视频', audio: '语音', asset: '资产' } as const;

export function Workbench({ node, models, connected, onChange, onRun, onClose, onDelete, onDuplicate }: Props) {
  if (!node) return <div className="workbench empty-workbench"><span>选择画布节点，打开工作台</span><small>双击空白处或使用底部“＋”添加节点</small></div>;
  const data = node.data;
  const config = data.config;
  const typeModels = models.filter((model) => model.type === (data.type === 'asset' ? 'image' : data.type));
  const cap = typeModels.find((model) => model.id === config.modelId)?.capability;
  const setConfig = (key: string, value: unknown) => onChange({ config: { ...config, [key]: value } });
  const field = (key: string, fallback = '') => String(config[key] ?? fallback);
  const numberField = (key: string, fallback: number) => Number(config[key] ?? fallback);

  return <section className="workbench">
    <div className="workbench-top"><div><span className="eyebrow">NODE WORKBENCH</span><h2>{data.label}<small>{data.subtitle}</small></h2></div><div className="workbench-actions"><button onClick={onDuplicate} title="复制节点">⧉</button><button onClick={onClose} title="关闭工作台">×</button></div></div>
    {data.type === 'asset' ? <div className="asset-workbench"><div className="asset-workbench-preview">{data.assetUrl ? <img src={data.assetUrl} alt="" /> : '◈'}</div><div><strong>{data.label}</strong><p>资产引用节点可以连接到图片、视频或语音生成节点。</p><span className="chip">{labelMap[data.assetKind ?? 'image']}</span></div></div> : <>
      <div className="workbench-toolbar"><button>＋ 参考</button><button>⌁ 标记</button><button>✦ 特效</button><button>◌ 角色库</button><button>▣ 运镜</button></div>
      <textarea className="workbench-prompt" value={data.body} onChange={(event) => onChange({ body: event.target.value })} placeholder={data.type === 'audio' ? '输入要合成的文字内容…' : '描述你想生成的内容，@引用素材…'} />
      <div className="workbench-grid">
        <label>生成模型<select value={field('modelId')} onChange={(event) => setConfig('modelId', event.target.value)}>{typeModels.length ? typeModels.map((model) => <option key={model.id} value={model.id}>{model.name} · {model.provider}</option>) : <option>请先到设置中心添加模型</option>}</select></label>
        <label>模式<select value={field('mode')} onChange={(event) => setConfig('mode', event.target.value)}>{(cap?.modes ?? (data.type === 'image' ? ['图生图', '文生图'] : data.type === 'video' ? ['全能参考', '图生视频', '首尾帧'] : data.type === 'audio' ? ['文本转语音', '音色设计', '音色克隆'] : ['文本生成'])).map((item) => <option key={item}>{item}</option>)}</select></label>
      </div>
      {data.type === 'video' ? <div className="parameter-panel"><div className="param-title">视频参数</div><div className="param-row"><label>比例<select value={field('aspectRatio', '16:9')} onChange={(event) => setConfig('aspectRatio', event.target.value)}>{(cap?.aspectRatios ?? ['Auto', '16:9', '4:3', '1:1', '3:4', '9:16', '21:9']).map((item) => <option key={item}>{item}</option>)}</select></label><label>清晰度<select value={field('resolution', '720p')} onChange={(event) => setConfig('resolution', event.target.value)}>{(cap?.resolutions ?? ['480p', '720p', '1080p']).map((item) => <option key={item}>{item}</option>)}</select></label></div><div className="param-row"><label>视频时长<input type="number" min={3} max={30} value={numberField('duration', 5)} onChange={(event) => setConfig('duration', Number(event.target.value))} /></label><label>生成数量<select value={numberField('count', 1)} onChange={(event) => setConfig('count', Number(event.target.value))}>{(cap?.counts ?? [1, 2, 4]).map((item) => <option key={item} value={item}>{item} 个</option>)}</select></label></div><label className="switch-row"><span>生成音频</span><input type="checkbox" checked={Boolean(config.generateAudio)} onChange={(event) => setConfig('generateAudio', event.target.checked)} /></label></div> : null}
      {data.type === 'image' ? <div className="parameter-panel"><div className="param-title">图片参数</div><div className="param-row"><label>比例<select value={field('aspectRatio', '16:9')} onChange={(event) => setConfig('aspectRatio', event.target.value)}>{(cap?.aspectRatios ?? ['1:1', '16:9', '9:16', '4:3', '3:4']).map((item) => <option key={item}>{item}</option>)}</select></label><label>分辨率<select value={field('resolution', '2K')} onChange={(event) => setConfig('resolution', event.target.value)}>{(cap?.resolutions ?? ['1K', '2K']).map((item) => <option key={item}>{item}</option>)}</select></label></div><label>生成数量<select value={numberField('count', 1)} onChange={(event) => setConfig('count', Number(event.target.value))}><option value="1">1 张</option><option value="2">2 张</option><option value="4">4 张</option></select></label></div> : null}
      {data.type === 'audio' ? <div className="parameter-panel"><div className="param-title">语音参数</div><div className="param-row"><label>语言<select value={field('language', '中文')} onChange={(event) => setConfig('language', event.target.value)}>{(cap?.languages ?? ['中文', 'English']).map((item) => <option key={item}>{item}</option>)}</select></label><label>格式<select value={field('format', 'wav')} onChange={(event) => setConfig('format', event.target.value)}>{(cap?.formats ?? ['wav', 'mp3']).map((item) => <option key={item}>{item}</option>)}</select></label></div><label>采样率<select value={numberField('sampleRate', 24000)} onChange={(event) => setConfig('sampleRate', Number(event.target.value))}>{(cap?.sampleRates ?? [16000, 24000]).map((item) => <option key={item} value={item}>{item / 1000}k</option>)}</select></label><div className="range-row"><label>速度 <output>{field('speed', '1.0')}×</output><input type="range" min="0.5" max="2" step="0.1" value={numberField('speed', 1)} onChange={(event) => setConfig('speed', Number(event.target.value))} /></label><label>音调 <output>{field('pitch', '0')}</output><input type="range" min="-12" max="12" step="1" value={numberField('pitch', 0)} onChange={(event) => setConfig('pitch', Number(event.target.value))} /></label></div></div> : null}
      {data.type === 'text' ? <div className="parameter-panel"><div className="param-title">文字参数</div><label>系统提示词<textarea value={field('system')} onChange={(event) => setConfig('system', event.target.value)} placeholder="可选：定义模型的角色与输出格式" /></label><div className="param-row"><label>最大输出<input type="number" min={100} value={numberField('maxTokens', 1200)} onChange={(event) => setConfig('maxTokens', Number(event.target.value))} /></label><label>温度<input type="number" min={0} max={2} step={0.1} value={numberField('temperature', 0.7)} onChange={(event) => setConfig('temperature', Number(event.target.value))} /></label></div></div> : null}
      <div className="connected-row"><span>已连接引用</span><strong>{connected.length ? connected.join('、') : '暂无上游结果'}</strong></div>
      <div className="workbench-footer"><button className="danger-ghost" onClick={onDelete}>删除节点</button><button className="run-primary" onClick={onRun} disabled={data.status === 'running' || data.status === 'queued'}>{data.status === 'running' ? '生成中…' : data.status === 'queued' ? '排队中…' : '↑ 运行节点'}</button></div>
    </>}
  </section>;
}
