'use client';

import { useEffect, useMemo, useState } from 'react';
import { DEFAULT_MODELS } from '../../lib/canvas/registry';
import type { ModelConfig } from '../../lib/canvas/types';

type Provider = { id: string; name: string; protocol: string; baseUrl: string; apiKey: string; hidden: boolean; models: ModelConfig[] };
type SettingsState = { defaults: { models: ModelConfig[]; concurrency: { text: number; image: number; video: number; audio: number } }; providers: Provider[] };
const fallback: SettingsState = { defaults: { models: DEFAULT_MODELS, concurrency: { text: 5, image: 5, video: 5, audio: 5 } }, providers: [{ id: 'openrouter', name: 'OpenRouter', protocol: 'native', baseUrl: 'https://openrouter.ai/api/v1', apiKey: '', hidden: false, models: DEFAULT_MODELS.filter((model) => model.provider === 'OpenRouter') }, { id: 'mimo', name: '小米 MiMo', protocol: 'native', baseUrl: 'https://token-plan-cn.xiaomimimo.com/v1', apiKey: '', hidden: false, models: DEFAULT_MODELS.filter((model) => model.provider === '小米 MiMo') }, { id: 'compatible', name: 'OpenAI / Gemini Compatible', protocol: 'openai', baseUrl: '', apiKey: '', hidden: false, models: DEFAULT_MODELS.filter((model) => model.id.includes('compatible')) }] };
const typeName = { text: '文本', image: '图像', video: '视频', audio: '语音' } as const;

export default function SettingsClient() {
  const [state, setState] = useState<SettingsState>(fallback);
  const [loaded, setLoaded] = useState(false);
  const [providerModal, setProviderModal] = useState(false);
  const [newProvider, setNewProvider] = useState({ name: '', baseUrl: '', apiKey: '', protocol: 'openai' });
  const [activeType, setActiveType] = useState<keyof typeof typeName>('text');
  const [notice, setNotice] = useState('');
  const [modelDraft, setModelDraft] = useState({ name: '', modelId: '' });

  useEffect(() => { void fetch('/api/settings').then(async (response) => { if (response.status === 401) { const token = window.prompt('请输入工作区令牌'); if (token) { const login = await fetch('/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token }) }); if (login.ok) return fetch('/api/settings'); } } return response; }).then((response) => response.ok ? response.json() as Promise<SettingsState> : null).then((data) => { if (data) setState(data); }).catch(() => undefined).finally(() => setLoaded(true)); }, []);
  const save = async (next: SettingsState) => { setState(next); setNotice('已保存'); window.setTimeout(() => setNotice(''), 1800); await fetch('/api/settings', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ defaults: next.defaults }) }).catch(() => undefined); };
  const updateConcurrency = (type: keyof typeof typeName, value: number) => void save({ ...state, defaults: { ...state.defaults, concurrency: { ...state.defaults.concurrency, [type]: Math.max(1, value || 1) } } });
  const updateProvider = async (provider: Provider, patch: Partial<Provider>) => { const next = { ...provider, ...patch }; setState((current) => ({ ...current, providers: current.providers.map((item) => item.id === provider.id ? next : item) })); await fetch(`/api/providers/${provider.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(patch) }).catch(() => undefined); setNotice('已保存'); };
  const testProvider = async (provider: Provider) => { const response = await fetch(`/api/providers/${provider.id}/test`, { method: 'POST' }); const data = await response.json().catch(() => ({})) as { message?: string }; setNotice(data.message ?? (response.ok ? '连接成功' : '连接失败')); };
  const addProvider = async () => { if (!newProvider.name || !newProvider.baseUrl) return setNotice('请填写名称和 Base URL'); const response = await fetch('/api/providers', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(newProvider) }); const provider = await response.json() as Provider & { message?: string }; if (response.ok) { setState((current) => ({ ...current, providers: [...current.providers, provider] })); setProviderModal(false); setNewProvider({ name: '', baseUrl: '', apiKey: '', protocol: 'openai' }); } setNotice(response.ok ? '服务商已添加' : provider.message ?? '添加失败'); };
  const addModel = async (provider: Provider) => { if (!modelDraft.name || !modelDraft.modelId) return; const model: ModelConfig = { id: `${provider.id}::${modelDraft.modelId}`, name: modelDraft.name, provider: provider.name, modelId: modelDraft.modelId, type: activeType, enabled: true }; const nextProvider = { ...provider, models: [...provider.models, model] }; const next = { ...state, providers: state.providers.map((item) => item.id === provider.id ? nextProvider : item), defaults: { ...state.defaults, models: [...state.defaults.models, model] } }; await updateProvider(provider, { models: nextProvider.models }); await save(next); setModelDraft({ name: '', modelId: '' }); };
  const models = useMemo(() => state.defaults.models.filter((model) => model.type === activeType), [activeType, state.defaults.models]);
  const modelFor = (type: keyof typeof typeName) => state.defaults.models.filter((model) => model.type === type);

  if (!loaded) return <div className="settings-page loading-settings">正在加载设置…</div>;
  return <main className="settings-page"><div className="settings-title"><span className="settings-logo">⚙</span><div><h1>设置</h1><p>管理你的 API 密钥和模型配置</p></div>{notice ? <span className="save-toast">{notice}</span> : null}</div>
    <section className="settings-shell"><div className="settings-section-head"><div><span className="eyebrow">API CONFIGURATION</span><h2>默认模型配置</h2><p>新建项目与资产库将使用此默认配置，也可在节点工作台中单独覆盖模型。</p></div></div>
      <h3 className="settings-group-title">⚡ 文本分析与视频能力</h3><div className="settings-cards two-cols"><div className="settings-card"><div className="card-top"><span className="card-icon blue">T</span><label>分析流程并发<input type="number" min="1" value={state.defaults.concurrency.text} onChange={(event) => updateConcurrency('text', Number(event.target.value))} /></label></div><h4>文本分析模型</h4><p>负责提示词整理、脚本解析和文字生成能力。</p><select value={modelFor('text')[0]?.id ?? ''} onChange={(event) => void save({ ...state, defaults: { ...state.defaults, models: state.defaults.models.map((model) => model.type === 'text' ? { ...model, enabled: model.id === event.target.value } : model) } })}>{modelFor('text').map((model) => <option key={model.id} value={model.id}>{model.name} · {model.provider}</option>)}</select></div><div className="settings-card"><div className="card-top"><span className="card-icon purple">▶</span><label>视频流程并发<input type="number" min="1" value={state.defaults.concurrency.video} onChange={(event) => updateConcurrency('video', Number(event.target.value))} /></label></div><h4>视频生成模型</h4><p>负责将图像与指令合成为最终视频片段。</p><select value={modelFor('video').find((model) => model.enabled)?.id ?? ''} onChange={(event) => void save({ ...state, defaults: { ...state.defaults, models: state.defaults.models.map((model) => model.type === 'video' ? { ...model, enabled: model.id === event.target.value } : model) } })}>{modelFor('video').map((model) => <option key={model.id} value={model.id}>{model.name} · {model.provider}</option>)}</select></div></div>
      <div className="settings-group-row"><h3 className="settings-group-title">✦ 全局图像模型配置</h3><label>图像流程并发<input type="number" min="1" value={state.defaults.concurrency.image} onChange={(event) => updateConcurrency('image', Number(event.target.value))} /></label></div><div className="image-config"><div className="hint-box">推荐使用支持比例、分辨率和多图输出的图片模型。节点工作台会根据模型能力显示对应参数。</div><div className="unified-config"><div><strong>批量配置图像模型</strong><small>设置负责整个项目图片生成和编辑的默认模型</small></div><select value={modelFor('image')[0]?.id ?? ''} onChange={(event) => void save({ ...state, defaults: { ...state.defaults, models: state.defaults.models.map((model) => model.type === 'image' ? { ...model, enabled: model.id === event.target.value } : model) } })}>{modelFor('image').map((model) => <option key={model.id} value={model.id}>{model.name} · {model.provider}</option>)}</select></div><div className="pipeline-grid">{['角色生成', '场景生成', '镜头生成', '编辑图片'].map((item) => <div className="pipeline-card" key={item}><span>▧</span><b>{item}</b><small>{modelFor('image').find((model) => model.enabled)?.name ?? '跟随统一配置'}</small></div>)}</div></div>
      <h3 className="settings-group-title">◇ 扩展功能</h3><div className="settings-cards three-cols">{(['audio', 'video', 'text'] as const).map((type, index) => <div className="settings-card compact" key={type}><h4>{index === 0 ? '语音合成' : index === 1 ? '视频参考' : '文字生成'}</h4><select value={modelFor(type)[0]?.id ?? ''} onChange={(event) => void save({ ...state, defaults: { ...state.defaults, models: state.defaults.models.map((model) => model.type === type ? { ...model, enabled: model.id === event.target.value } : model) } })}>{modelFor(type).map((model) => <option key={model.id} value={model.id}>{model.name}</option>)}</select></div>)}</div>
    </section>
    <section className="settings-shell providers-section"><div className="settings-section-head provider-head"><div><span className="eyebrow">PROVIDER RESOURCE POOL</span><h2>厂商资源池</h2><p>在此配置模型服务商、API Key、模型分类和默认能力。</p></div><button className="accent-button" onClick={() => setProviderModal(true)}>＋ 新增模型服务商</button></div><div className="provider-tabs">{(['text', 'image', 'video', 'audio'] as const).map((type) => <button key={type} className={activeType === type ? 'active' : ''} onClick={() => setActiveType(type)}>{typeName[type]} <span>{models.filter((model) => model.type === type).length}</span></button>)}</div><div className="provider-list">{state.providers.filter((provider) => !provider.hidden).map((provider) => <article className="provider-card" key={provider.id}><div className="provider-card-head"><div className="drag-handle">⠿</div><div><h3>{provider.name}</h3><small>{provider.protocol === 'native' ? '官方 API' : 'OpenAI / Gemini 兼容层'}</small></div><span className="connected-dot">{provider.apiKey ? '已连接' : '未配置'}</span><button onClick={() => void updateProvider(provider, { hidden: true })}>隐藏提供商</button></div><div className="provider-fields"><label>API Key<div className="secret-field"><input type="password" placeholder={provider.apiKey || '输入 API Key'} onBlur={(event) => event.target.value && void updateProvider(provider, { apiKey: event.target.value })} /><span>••••••</span></div></label><label>Base URL<input value={provider.baseUrl} onChange={(event) => setState((current) => ({ ...current, providers: current.providers.map((item) => item.id === provider.id ? { ...item, baseUrl: event.target.value } : item) }))} onBlur={(event) => void updateProvider(provider, { baseUrl: event.target.value })} /></label><div className="provider-actions"><button onClick={() => void testProvider(provider)}>测试连接</button><button onClick={() => void updateProvider(provider, { hidden: true })}>删除/隐藏</button></div></div><div className="provider-models"><div className="model-table-head"><b>{typeName[activeType]}模型</b><span>{provider.models.filter((model) => model.type === activeType).length} 个</span></div>{provider.models.filter((model) => model.type === activeType).map((model) => <div className="model-line" key={model.id}><span className="model-bullet">{typeName[model.type][0]}</span><div><strong>{model.name}</strong><small>{model.modelId}</small></div><span className="default-tag">{model.enabled ? '默认' : '可用'}</span><button>配置</button></div>)}<div className="add-model-line"><input placeholder="模型显示名称" value={modelDraft.name} onChange={(event) => setModelDraft({ ...modelDraft, name: event.target.value })} /><input placeholder="模型 ID" value={modelDraft.modelId} onChange={(event) => setModelDraft({ ...modelDraft, modelId: event.target.value })} /><button onClick={() => void addModel(provider)}>＋ 添加</button></div></div></article>)}</div></section>
    {providerModal ? <div className="modal-backdrop" onClick={() => setProviderModal(false)}><div className="provider-modal" onClick={(event) => event.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">PROVIDER</span><h2>新增模型服务商</h2></div><button onClick={() => setProviderModal(false)}>×</button></div><p>支持 OpenAI 兼容和 Gemini 兼容接口，密钥只会在服务端使用。</p><label>API 类型<select value={newProvider.protocol} onChange={(event) => setNewProvider({ ...newProvider, protocol: event.target.value })}><option value="openai">OpenAI 兼容</option><option value="gemini">Gemini 兼容</option></select></label><label>名称<input value={newProvider.name} onChange={(event) => setNewProvider({ ...newProvider, name: event.target.value })} placeholder="例如：我的图片服务" /></label><label>Base URL<input value={newProvider.baseUrl} onChange={(event) => setNewProvider({ ...newProvider, baseUrl: event.target.value })} placeholder="https://api.example.com/v1" /></label><label>API Key<input type="password" value={newProvider.apiKey} onChange={(event) => setNewProvider({ ...newProvider, apiKey: event.target.value })} /></label><div className="modal-actions"><button onClick={() => setProviderModal(false)}>取消</button><button className="accent-button" onClick={() => void addProvider()}>添加</button></div></div></div> : null}
  </main>;
}
